# Generated by Django 3.2.4 on 2021-07-05 09:24

from django.db import migrations, models
import django.db.models.deletion
import versatileimagefield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Programmer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('programmer_name', models.CharField(max_length=50)),
                ('programmer_surname', models.CharField(max_length=50)),
                ('programmer_deadline', models.DateField()),
                ('programmer_birthday', models.DateField()),
                ('programmer_rank', models.CharField(max_length=50)),
                ('programmer_image', versatileimagefield.fields.VersatileImageField(blank=True, upload_to='profile')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, verbose_name='shortcut')),
                ('project_name', models.CharField(max_length=25, unique=True)),
                ('project_detail', models.CharField(max_length=150)),
                ('project_image', versatileimagefield.fields.VersatileImageField(upload_to='media')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(max_length=25, unique=True)),
                ('task_description', models.CharField(max_length=150)),
                ('task_startwork', models.DateField()),
                ('task_deadline', models.DateField()),
                ('task_type', models.CharField(choices=[('1', 'Feature'), ('2', 'Bug')], default=None, max_length=20)),
                ('task_programmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.programmer')),
            ],
        ),
        migrations.AddField(
            model_name='programmer',
            name='programmer_project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.project'),
        ),
    ]
